#!/bin/sh
# Keep /boot/vmlinuz.efi in step with /boot/vmlinuz, for the EFI boot paths.
#
# STOPGAP. The right place for this is the kernel package, which has the
# uncompressed Image already and can install it directly; that change is made
# but only takes effect the next time the kernel is actually rebuilt. Delete
# this hook, and its install line, once a kernel carrying /boot/vmlinuz.efi
# has shipped.
#
# Why the file is needed at all: zinstall puts Image.gz at /boot/vmlinuz, which
# is what U-Boot's booti wants -- it decompresses -- and therefore what
# extlinux and the direct rootfs boot use. systemd-boot cannot use it. It loads
# `linux` as an EFI application and does not decompress, so a gzipped vmlinuz
# just fails. boot-deploy knows this and points the loader entry at
# vmlinuz.efi whenever one exists; see generate_bootloader_spec_conf().
#
# Why not CONFIG_EFI_ZBOOT=y, which exists for exactly this: it makes zinstall
# write the self-decompressing PE to /boot/vmlinuz itself
# (arch/arm64/boot/install.sh maps both Image.gz and vmlinuz.efi to the name
# "vmlinuz"), leaving nothing bootable for booti. U-Boot's extlinux support has
# no bootefi path -- label_boot() in boot/pxe_utils.c tries bootm, booti, bootz
# and x86 zboot, and stops. Enabling ZBOOT would fix systemd-boot and break
# extlinux and the rootfs fallback in the same change.
#
# Why a hook and not a one-off file: generated by hand the two drift, and a
# STALE vmlinuz.efi is worse than a missing one. boot-deploy prefers it, so the
# handset would boot an old kernel against new modules in /usr/lib/modules,
# silently and successfully. boot-deploy runs this before it writes the loader
# entry, and /boot/vmlinuz is already the new kernel by then -- apk installs it
# before the mkinitfs trigger fires.
#
# This runs on every boot-deploy invocation, so it must be quiet and must never
# leave a half-written file in place.

set -e

[ -f /boot/vmlinuz ] || exit 0

# If vmlinuz is already a PE image (ZBOOT, or a kernel package that ships one),
# there is nothing to do and nothing to keep in step.
case "$(dd if=/boot/vmlinuz bs=2 count=1 2>/dev/null | od -An -c | tr -d ' \n')" in
	MZ*) exit 0 ;;
esac

# Only gzip is handled; anything else means the packaging changed and this
# hook's assumption no longer holds, so say so rather than writing nonsense.
case "$(dd if=/boot/vmlinuz bs=2 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n')" in
	1f8b) ;;
	*)
		echo "50-fogona-vmlinuz-efi: /boot/vmlinuz is neither gzip nor PE;"
		echo "50-fogona-vmlinuz-efi: leaving /boot/vmlinuz.efi alone."
		exit 0
		;;
esac

_tmp=/boot/vmlinuz.efi.new
rm -f "$_tmp"
zcat /boot/vmlinuz > "$_tmp"

# The decompressed Image must be a valid EFI application, which it is when the
# kernel has CONFIG_EFI_STUB=y: it starts "MZ" and carries the arm64 "ARMd"
# magic at 0x38. Refuse to install one that does not, rather than handing
# systemd-boot something it will fail on at boot with no console to report it.
case "$(dd if=$_tmp bs=2 count=1 2>/dev/null | od -An -c | tr -d ' \n')" in
	MZ*) ;;
	*)
		rm -f "$_tmp"
		echo "50-fogona-vmlinuz-efi: decompressed kernel is not a PE image"
		echo "50-fogona-vmlinuz-efi: (CONFIG_EFI_STUB off?); not installing."
		exit 0
		;;
esac

mv "$_tmp" /boot/vmlinuz.efi
sync
